<a href="https://colab.research.google.com/github/mun387344/diabetic-readmission-prediction/blob/main/notebooks/01_data_exploration_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **RULE: EVERYONE SHOULD CONTRIBBUTE FOR EACH PART.**

### **Import Libraries**

In [ ]:
import pandas as pd   #Hey! Import libraries when you actually need them (Muna)
import numpy as np

### **Load Dataset**

In [ ]:
df = pd.read_csv('/content/diabetic_data.csv')  #Hey guys! anytime you open the collab, you should upload your local path to run it.

In [ ]:
df.head()   #Muna

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

### **Understand Dataset**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB

In [ ]:
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [ ]:
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

###Exploring Dataset

### **Check missing values, Duplicates, Class distribution and Inspect Unusual Values**

In [ ]:
#Unique Values
df.nunique().sort_values()

citoglipton                      1
examide                          1
acetohexamide                    2
glipizide-metformin              2
tolbutamide                      2
troglitazone                     2
metformin-rosiglitazone          2
glimepiride-pioglitazone         2
metformin-pioglitazone           2
change                           2
diabetesMed                      2
gender                           3
tolazamide                       3
readmitted                       3
max_glu_serum                    3
A1Cresult                        3
acarbose                         4
rosiglitazone                    4
pioglitazone                     4
miglitol                         4
glimepiride                      4
metformin                        4
nateglinide                      4
repaglinide                      4
chlorpropamide                   4
glipizide                        4
glyburide                        4
insulin                          4
glyburide-metformin              4
race                             6
num_procedures                   7
admission_type_id                8
age                             10
weight                          10
time_in_hospital                14
number_diagnoses                16
admission_source_id             17
payer_code                      18
number_inpatient                21
discharge_disposition_id        26
number_emergency                33
number_outpatient               39
medical_specialty               73
num_medications                 75
num_lab_procedures             118
diag_1                         717
diag_2                         749
diag_3                         790
patient_nbr                  71518
encounter_id                101766
dtype: int64

In [ ]:
#Unique values present in "weight" column
df["weight"].unique()

array(['?', '[75-100)', '[50-75)', '[0-25)', '[100-125)', '[25-50)',
       '[125-150)', '[175-200)', '[150-175)', '>200'], dtype=object)

In [ ]:
#how many times each unique value appears in the "weight" column, including any missing or null values.
df["weight"].value_counts(dropna=False)

weight
?            98569
[75-100)      1336
[50-75)        897
[100-125)      625
[125-150)      145
[25-50)         97
[0-25)          48
[150-175)       35
[175-200)       11
>200             3
Name: count, dtype: int64

In [ ]:
#how many ? values exist in each column.
(df == "?").sum()

encounter_id                    0
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [ ]:
#Target Distribution
df["readmitted"].value_counts()

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [ ]:
#Percentage of Target Distribution
df["readmitted"].value_counts(normalize=True) * 100

readmitted
NO     53.911916
>30    34.928169
<30    11.159916
Name: proportion, dtype: float64

In [ ]:
#Duplicates
df.duplicated().sum()

np.int64(0)

###Cleaning Dataset

In [ ]:
#Keep a copy of row data for cleaning
df_clean = df.copy()

In [ ]:
#No Duplicate Values
df_clean.duplicated().sum()

np.int64(0)

Investigate "?" values

In [ ]:
#Convert ? into actual missing values (NaN).
df_clean = df_clean.replace("?", np.nan)

In [ ]:
df_clean.isnull().sum()

race                        0
gender                      0
age                         0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [ ]:
df_clean["diag_1"].value_counts(dropna=False).head(20)

diag_1
428      6862
414      6581
786      4016
410      3614
486      3508
427      2766
491      2275
715      2151
682      2042
434      2028
780      2019
996      1967
276      1889
38       1688
250.8    1680
599      1595
584      1520
V57      1207
250.6    1183
518      1115
Name: count, dtype: int64

In [ ]:
df_clean["diag_2"].value_counts(dropna=False).head(20)

diag_2
276       6752
428       6662
250       6071
427       5036
401       3736
496       3305
599       3288
403       2823
414       2650
411       2566
250.02    2074
707       1999
585       1871
584       1649
491       1545
250.01    1523
285       1520
780       1491
425       1434
682       1433
Name: count, dtype: int64

In [ ]:
df_clean["diag_3"].value_counts(dropna=False).head(20)

diag_3
250        11555
401         8289
276         5175
428         4577
427         3955
414         3664
496         2605
403         2357
585         1992
272         1969
599         1941
Unknown     1423
V45         1389
250.02      1369
707         1360
780         1334
285         1200
425         1136
250.6       1080
424         1063
Name: count, dtype: int64

Checking all categorical columns

In [ ]:
df_clean["race"].value_counts(dropna=False)

race
Caucasian          76099
AfricanAmerican    19210
Unknown             2273
Hispanic            2037
Other               1506
Asian                641
Name: count, dtype: int64

In [ ]:
df_clean["gender"].value_counts(dropna=False)

gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

In [ ]:
df_clean["age"].value_counts(dropna=False)

age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20)       691
[0-10)        161
Name: count, dtype: int64

In [ ]:
df_clean["max_glu_serum"].value_counts(dropna=False)

KeyError: 'max_glu_serum'

In [ ]:
df_clean["A1Cresult"].value_counts(dropna=False)

KeyError: 'A1Cresult'

In [ ]:
df_clean["medical_specialty"].value_counts(dropna=False)

medical_specialty
Unknown                   49949
InternalMedicine          14635
Emergency/Trauma           7565
Family/GeneralPractice     7440
Cardiology                 5352
                          ...
Proctology                    1
Speech                        1
SportsMedicine                1
Perinatology                  1
Neurophysiology               1
Name: count, Length: 73, dtype: int64

In [ ]:
#Check the numerical columns for strange values
df_clean[[
    "time_in_hospital",
    "num_lab_procedures",
    "num_procedures",
    "num_medications",
    "number_outpatient",
    "number_emergency",
    "number_inpatient",
    "number_diagnoses"
]].describe()

,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [ ]:
df_clean.columns.tolist()

['race',
 'gender',
 'age',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'payer_code',
 'medical_specialty',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'diag_1',
 'diag_2',
 'diag_3',
 'number_diagnoses',
 'metformin',
 'repaglinide',
 'nateglinide',
 'chlorpropamide',
 'glimepiride',
 'acetohexamide',
 'glipizide',
 'glyburide',
 'tolbutamide',
 'pioglitazone',
 'rosiglitazone',
 'acarbose',
 'miglitol',
 'troglitazone',
 'tolazamide',
 'examide',
 'citoglipton',
 'insulin',
 'glyburide-metformin',
 'glipizide-metformin',
 'glimepiride-pioglitazone',
 'metformin-rosiglitazone',
 'metformin-pioglitazone',
 'change',
 'diabetesMed',
 'readmitted']

In [ ]:
"max_glu_serum" in df_clean.columns
"A1Cresult" in df_clean.columns

False

In [ ]:
df_clean.shape

(101766, 45)

In [ ]:
# Missing Values


def count_missing_custom(col):
    return col.astype(str).isin(['?', 'None', 'nan', '']).sum()

missing_counts = df.apply(count_missing_custom)
missing_pct = (missing_counts / len(df)) * 100
missing_df = pd.DataFrame({'Count': missing_counts, 'Percentage': missing_pct})
print("\nColumns with Missing Values (sorted by %):")
print(missing_df[missing_df['Count'] > 0].sort_values(by='Percentage', ascending=False))

# 4. Duplicates
print(f"\nNumber of exact duplicate rows: {df.duplicated().sum()}")

# 5. Class Distribution (Target Variable)
print("\nClass Distribution ('readmitted'):")
print(df['readmitted'].value_counts())

# 6. Inspect Unusual Values
print("\nUnique values in 'age' (binned):", df['age'].unique())
print("Unique values in 'weight' (binned sample):", df['weight'].unique()[:5])
print("Unique values in 'gender':", df['gender'].unique())
print("Unique values in 'race':", df['race'].unique())
print("\nSummary Statistics:")
display(df.describe(include="all"))

Columns with Missing Values (sorted by %):
                   Count  Percentage
weight             98569   96.858479
max_glu_serum      96420   94.746772
A1Cresult          84748   83.277322
medical_specialty  49949   49.082208
payer_code         40256   39.557416
race                2273    2.233555
diag_3              1423    1.398306
diag_2               358    0.351787
diag_1                21    0.020636

Number of exact duplicate rows: 0

Class Distribution ('readmitted'):
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

Unique values in 'age' (binned): ['[0-10)' '[10-20)' '[20-30)' '[30-40)' '[40-50)' '[50-60)' '[60-70)'
 '[70-80)' '[80-90)' '[90-100)']
Unique values in 'weight' (binned sample): ['?' '[75-100)' '[50-75)' '[0-25)' '[100-125)']
Unique values in 'gender': ['Female' 'Male' 'Unknown/Invalid']
Unique values in 'race': ['Caucasian' 'AfricanAmerican' '?' 'Other' 'Asian' 'Hispanic']

Summary Statistics:

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
count,1.017660e+05,1.017660e+05,101766,101766,101766,101766,101766.000000,101766.000000,101766.000000,101766.000000,...,101766,101766,101766,101766,101766,101766,101766,101766,101766,101766
unique,NaN,NaN,6,3,10,10,NaN,NaN,NaN,NaN,...,1,4,4,2,2,2,2,2,2,3
top,NaN,NaN,Caucasian,Female,[70-80),?,NaN,NaN,NaN,NaN,...,No,No,No,No,No,No,No,No,Yes,NO
freq,NaN,NaN,76099,54708,26068,98569,NaN,NaN,NaN,NaN,...,101766,47383,101060,101753,101765,101764,101765,54755,78363,54864
mean,1.652016e+08,5.433040e+07,NaN,NaN,NaN,NaN,2.024006,3.715642,5.754437,4.395987,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.026403e+08,3.869636e+07,NaN,NaN,NaN,NaN,1.445403,5.280166,4.064081,2.985108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.252200e+04,1.350000e+02,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,8.496119e+07,2.341322e+07,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,2.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.523890e+08,4.550514e+07,NaN,NaN,NaN,NaN,1.000000,1.000000,7.000000,4.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2.302709e+08,8.754595e+07,NaN,NaN,NaN,NaN,3.000000,4.000000,7.000000,6.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,4.438672e+08,1.895026e+08,NaN,NaN,NaN,NaN,8.000000,28.000000,25.000000,14.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### **Data Cleaning [Mohammed]**

In [ ]:

print(f"--- Initial Dataset Shape: {df.shape} ---\n")

# LOG ENTRY 1: Standardize Missing Values

missing_q_count = (df == '?').sum()
df.replace('?', np.nan, inplace=True)
print(f"[Log 1] Replaced {missing_q_count} '?' instances with np.nan.")

# LOG ENTRY 2: Drop Identifiers

ids_to_drop = ['encounter_id', 'patient_nbr']
df.drop(columns=ids_to_drop, inplace=True, errors='ignore')
print(f"[Log 2] Dropped {len(ids_to_drop)} identifier columns.")

# LOG ENTRY 3: Drop Extreme Missingness Columns

high_missing_cols = ['weight', 'max_glu_serum', 'A1Cresult']
df.drop(columns=high_missing_cols, inplace=True)

print(f"[Log 3] Dropped columns with >80% missingness.")

# LOG ENTRY 4: Impute Categorical Missingness

cat_cols = df.select_dtypes(include=['object']).columns
cat_missing_before = df[cat_cols].isna().sum()

# Fill missing categorical data with 'Unknown'
df[cat_cols] = df[cat_cols].fillna('Unknown')

print(f"[Log 4] Imputed categorical missing values with 'Unknown'. Affected observations:")
for col, count in cat_missing_before.items():
    if count > 0:
        print(f"   - {col}: {count} observations")

# LOG ENTRY 5: Encode Target Variable

if df['readmitted'].dtype == 'object':
    target_mapping = {'NO': 0, '>30': 1, '<30': 2}
    df['readmitted'] = df['readmitted'].map(target_mapping)
print(f"\n[Log 5] Encoded target variable 'readmitted' to numerical classes (0, 1, 2).")

# LOG ENTRY 6: Precautionary Numerical Imputation

num_cols = [col for col in df.columns if df[col].dtype != 'object' and col != 'readmitted']
num_missing_count = df[num_cols].isna().sum()

if num_missing_count.sum() > 0:
    for col in num_cols:
        df[col].fillna(df[col].median(), inplace=True)
    print(f"[Log 6] Imputed {num_missing_count.sum()} missing numerical values with median.")
else:
    print(f"[Log 6] Checked numerical columns: 0 missing values found.")

print(f"\n--- Final Cleaned Dataset Shape: {df.shape} ---")
if 'readmitted' in df.columns:
    print(f"Target Variable Distribution:\n{df['readmitted'].value_counts().sort_index()}")

--- Initial Dataset Shape: (101766, 50) ---

[Log 1] Replaced encounter_id                    0
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64 '?' instances with np.nan.
[Log 2] Dropped 2 identifier columns.
[Log 3] Dropped columns with >80% missingness.
[Log 4] Imputed categorical missing values with 'Unknown'. Affected observations:
   - race: 2273 observations
   - payer_code: 40256 observations
   - medical_specialty: 49949 observations
   - diag_1: 21 observations
   - diag_2: 358 observations
   - diag_3: 1423 observations

[Log 5] Encoded target variable 'readmitted' to numerical classes (0, 1, 2).
[Log 6] Checked numerical columns: 0 missing values found.

--- Final Cleaned Dataset Shape: (101766, 45) ---
Target Variable Distribution:
readmitted
0    54864
1    35545
2    11357
Name: count, dtype: int64